
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MARCADOR_FIN_SENTENCIA = 6;
  public static final int error = 1;
  public static final int OP_ESCRITURA = 5;
  public static final int LITERAL_CADENA = 7;
  public static final int LLAVE_DER = 4;
  public static final int LLAVE_IZQ = 3;
  public static final int EOF = 0;
  public static final int PROGRAMA = 2;
  public static final int TIPO = 8;
  public static final int MIENTRAS = 9;
  public static final int OP_LECTURA = 10;
  public static final int DIGITO = 11;
  public static final int IF = 12;
  public static final int ELSE = 13;
  public static final int ASIGNACION = 14;
  public static final int IGUAL = 15;
  public static final int ENTONCES = 16;
  public static final int OP_BIN = 17;
  public static final int INICIO = 18;
  public static final int FIN = 19;
  public static final int FOR = 20;
  public static final int VER = 21;
  public static final int FAL = 22;
  public static final int COMMT = 23;
  public static final int NO = 24;
  public static final int ID = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMA",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "OP_ESCRITURA",
  "MARCADOR_FIN_SENTENCIA",
  "LITERAL_CADENA",
  "TIPO",
  "MIENTRAS",
  "OP_LECTURA",
  "DIGITO",
  "IF",
  "ELSE",
  "ASIGNACION",
  "IGUAL",
  "ENTONCES",
  "OP_BIN",
  "INICIO",
  "FIN",
  "FOR",
  "VER",
  "FAL",
  "COMMT",
  "NO",
  "ID"
  };
}

